return {
	sword = {
		name = "Sword",
		description = "A sharp blade for combat.",
		color = { { 0.8, 0.8, 0.8, 1 } },
		slot = "mainhand",
		chars = { "/" },
		volume = 6,
		modifiers = {
			{ stat = "damage", op = "add", value = 3 },
		},
	},
	bow = {
		name = "Bow",
		description = "A keen bow for combat.",
		color = { { 0.8, 0.8, 0.8, 1 } },
		slot = "mainhand",
		chars = { "D" },
		modifiers = {
			{ stat = "damage", op = "add", value = 2 },
		},
		ranged = true,
		volume = 6,
		reach = 8,
		tags = { requires_ammo = true },
		range = 15,
	},
	arrow = {
		name = "Arrow",
		description = "Sharp arrows for combat.",
		color = { { 0.8, 0.8, 0.8, 1 } },
		chars = { "/" },
		slot = "ammo",
		charges = 1,
		modifiers = {
			{ stat = "damage", op = "add", value = 1 },
		},
		tags = {
			stacks = true,
		},
	},
	plank = {
		name = "Plank",
		description = "Can be used to barricade walls and windows.",
		color = { { 0.8, 0.7, 0.5, 1 } },
		on_use = { apply_status = "barricaded", target_tag = "barricadeable", targets = true },
		chars = { "=" },
		charges = 1,
		tags = {
			stacks = true,
		},
	},
	bandage = {
		name = "Bandages",
		description = "Can be used to bandage wounds.",
		color = { { 0.7, 0.7, 0.8, 1 } },
		on_use = { clear_status = "bandageable", burst = { type = "heal", count = 3 } },
		chars = { "~" },
		charges = 1,
		tags = {
			stacks = true,
		},
	},
	splint = {
		name = "Splint",
		description = "Can be used to splint broken bones.",
		color = { { 0.65, 0.7, 0.5, 1 } },
		on_use = { clear_status = "splintable", burst = { type = "heal", count = 3 } },
		chars = { "/" },
		charges = 1,
	},
	health_potion = {
		name = "Health Potion",
		description = "Restores health when consumed.",
		color = { { 1, 0.5, 0.5, 1 } },
		chars = { "&" },
		on_use = { apply_status = "regen" },
		charges = 3,
		max_charges = 3,
	},
	strength_potion = {
		name = "Strength Potion",
		description = "Improves strength when consumed.",
		color = { { 1, 0.5, 0.5, 1 } },
		chars = { "&" },
		on_use = { apply_status = "strength" },
		charges = 1,
	},
	leather_armor = {
		name = "Leather Armor",
		description = "Provides protection against attacks.",
		color = { { 0.5, 0.5, 0.7, 1 } },
		chars = { "A" },
		slot = "armor",
		modifiers = {
			{ stat = "health", op = "add", value = 5 },
		},
	},
	torch = {
		name = "Torch",
		description = "Provides light in dark areas.",
		color = { { 1, 0.35, 0.1, 1 } },
		chars = { "Y" },
		slot = "offhand",
		light = {
			color = { r = 1.0, g = 0.85, b = 0.55 },
			flicker = { amp = 0.05, freq = 8, phase = 4 },
			intensity = 0.5,
			radius = 6,
		},
	},
}
