return {
	player = {
		appearance = {
			chars = { "@" },
			color = { { 0.8, 0.8, 0.9, 1 } },
			effect_color = { 0.45, 0.45, 0.5, 0.5 },
		},
		name = "Player",
		team = "player",
		type = "actor",
		combat = { hit_burst = "blood" },
		tags = { covers = true, attackable = true, can_hear = true },
		default_action = "attackable",
		can_perform = {
			attackable = true,
			moveable = true,
			interactable = true,
			pickupable = true,
			vaultable = true,
		},
		stats = {
			health = { base = 35, current = 35 },
			stamina = { base = 10, current = 10 },
			hunger = { base = 10, current = 10 },
			sight = { base = 30 },
			stealth = { base = 10 },
			speed = { base = 5 },
			damage = { base = 1 },
		},
	},
	zombie = {
		name = "Zombie",
		type = "actor",
		team = "enemy",
		mind = { state = "idle" },
		appearance = {
			chars = { "Z" },
			color = { { 0.3, 0.45, 0.25, 1 } },
			effect_color = { 0.35, 0.6, 0.3, 0.5 },
		},
		description = "A zombie, try attacking it!",
		default_action = "attackable",
		combat = {
			attack_volume = 8,
			attack_sound = "a thump",
			hit_burst = "blood",
		},
		stats = {
			health = { base = 10, current = 10 },
			sight = { base = 30 },
			speed = { base = 4 },
			damage = { base = 1 },
		},
		tags = {
			moveable = true,
			covers = true,
			attackable = true,
			can_hear = true,
		},
		can_perform = {
			attackable = true,
			vaultable = true,
		},
	},
	shambler = {
		name = "Shambler",
		type = "actor",
		team = "enemy",
		mind = { state = "idle" },
		appearance = {
			chars = { "S" },
			color = { { 0.35, 0.45, 0.23, 1 } },
			effect_color = { 0.35, 0.6, 0.3, 0.5 },
		},
		description = "A shambler, try attacking it!",
		default_action = "attackable",
		combat = {
			attack_volume = 8,
			attack_sound = "a thump",
			applies_on_hit = { { name = "poison", chance = 50 } },
			hit_burst = "blood",
		},
		stats = {
			health = { base = 10, current = 10 },
			sight = { base = 30 },
			speed = { base = 4 },
			damage = { base = 1 },
		},
		tags = {
			moveable = true,
			covers = true,
			attackable = true,
			can_hear = true,
		},
		can_perform = {
			attackable = true,
		},
	},
	ogre = {
		name = "Ogre",
		type = "actor",
		team = "enemy",
		mind = { state = "idle" },
		appearance = {
			chars = { "O" },
			color = { { 0.5, 0.45, 0.25, 1 } },
			effect_color = { 0.5, 0.45, 0.25, 0.5 },
		},

		footprint = {
			{ dx = 0, dy = 0, char = "O" },
			{ dx = 1, dy = 0, char = "G" },
			{ dx = 0, dy = 1, char = "R" },
			{ dx = 1, dy = 1, char = "E" },
		},
		description = "An ogre, try attacking it!",
		default_action = "attackable",
		combat = {
			attack_volume = 16,
			attack_reach = 20,
			attack_sound = "a thud",
			applies_on_hit = { { name = "stun", chance = 50 } },
			hit_burst = "blood",
		},
		stats = {
			health = { base = 30, current = 30 },
			sight = { base = 30 },
			speed = { base = 3 },
			damage = { base = 3 },
		},
		tags = {
			moveable = true,
			covers = true,
			attackable = true,
			can_hear = true,
		},
		can_perform = {
			attackable = true,
		},
	},
	dragon = {
		name = "Dragon",
		type = "actor",
		team = "enemy",
		mind = { state = "idle" },
		appearance = {
			chars = { "D" },
			color = { { 0.8, 0.05, 0.05, 1 } },
			effect_color = { 0.85, 0.1, 0.05, 0.4 },
		},
		footprint = {
			{ dx = 0, dy = 0, char = "R" },
			{ dx = 1, dy = 0, char = "E" },
			{ dx = 2, dy = 0, char = "D" },
			{ dx = 0, dy = 1, char = "D" },
			{ dx = 1, dy = 1, char = "R" },
			{ dx = 2, dy = 1, char = "A" },
			{ dx = 0, dy = 2, char = "G" },
			{ dx = 1, dy = 2, char = "O" },
			{ dx = 2, dy = 2, char = "N" },
		},
		description = "A dragon, try attacking it!",
		default_action = "attackable",
		combat = {
			attack_volume = 16,
			attack_reach = 20,
			attack_sound = "a crash",
			applies_on_hit = { { name = "burning", chance = 50 } },
			hit_burst = "blood",
			attack_burst = "ember",
		},
		stats = {
			health = { base = 30, current = 30 },
			sight = { base = 30 },
			speed = { base = 5 },
			damage = { base = 3 },
		},
		tags = {
			moveable = true,
			covers = true,
			attackable = true,
			can_hear = true,
		},
		can_perform = {
			attackable = true,
		},
	},
	vampire = {
		name = "Vampire",
		type = "actor",
		team = "enemy",
		mind = { state = "idle" },
		appearance = {
			chars = { "V" },
			color = { { 0.7, 0.2, 0.2, 1 } },
			effect_color = { 0.35, 0.1, 0.1, 0.5 },
		},
		description = "A vampire, try attacking it!",
		default_action = "attackable",
		combat = {
			attack_volume = 2,
			attack_sound = "the scratch of claws and fangs",
			applies_on_hit = { { name = "bleeding", chance = 50 } },
			hit_burst = "blood",
		},
		stats = {
			health = { base = 10, current = 10 },
			sight = { base = 30 },
			speed = { base = 6 },
			damage = { base = 1 },
		},
		tags = {
			moveable = true,
			covers = true,
			attackable = true,
			can_hear = true,
		},
		can_perform = {
			attackable = true,
			interactable = true,
			vaultable = true,
		},
	},
	campfire = {
		name = "Campfire",
		type = "prop",
		appearance = {
			chars = { "%" },
			color = { { 1, 0.35, 0.1, 1 } },
		},
		description = "A Campfire",
		emitters = { { particle = "smoke", rate = 1 }, { particle = "ember", rate = 1.2 } },
		tags = {
			tilelike = true,
			covers = true,
		},
		light = {
			color = { r = 1.0, g = 0.6, b = 0.25 },
			intensity = 1,
			radius = 10,
			flicker = { amp = 0.02, freq = 2, phase = 3 },
		},
	},
	crystal = {
		name = "Crystal",
		type = "prop",
		appearance = {
			chars = { "<>", "<>" },
			color = { { 0.7, 0.9, 0.95, 1 } },
		},
		description = "A Crystal",
		default_action = "moveable",
		tags = {
			moveable = true,
			tilelike = true,
			covers = true,
		},
		light = {
			color = { r = 0.7, g = 0.9, b = 1 },
			intensity = 0.8,
			radius = 7,
			flicker = { amp = 0.05, freq = 4, phase = 0 },
		},
	},
	crate = {
		name = "Crate",
		description = "A heavy crate, try pushing it!",
		type = "prop",
		combat = { hit_burst = "dust" },
		appearance = {
			chars = { "#" },
			color = { { 0.38, 0.33, 0.30 } },
		},
		default_action = "moveable",
		stats = {
			health = { base = 5, current = 5 },
		},
		tags = {
			moveable = true,
			tilelike = true,
			covers = true,
			attackable = true,
		},
	},
	item = {
		name = "Item",
		description = "An item, try picking it up!",
		type = "prop",
		appearance = {
			chars = { "*" },
			color = { { 1, 1, 0, 1 } },
		},
		default_action = "pickupable",
		tags = {
			tilelike = true,
			covers = true,
			pickupable = true,
		},
	},
	barricade = {
		name = "Barricade",
		description = "A heavy barricade, try pushing it!",
		type = "prop",
		combat = { hit_burst = "dust" },
		appearance = {
			chars = { "[]", "[]" },
			color = { { 0.47, 0.23, 0.23, 1 } },
		},
		default_action = "moveable",
		stats = {
			health = { base = 10, current = 10 },
		},
		tags = {
			solid = true,
			moveable = true,
			tilelike = true,
			covers = true,
			attackable = true,
		},
	},
	door = {
		name = "Door",
		description = "A door, try opening it!",
		type = "prop",
		appearance = {
			chars = { "[", "[" },
			color = { { 0.30, 0.16, 0.06, 1 } },
		},
		default_action = "interactable",
		stats = {
			health = { base = 10, current = 10 },
		},
		combat = { hit_burst = "dust" },
		tags = {
			solid = true,
			walkable = false, -- swapped by interaction.toggle; must stay explicit
			tilelike = true,
			interactable = true,
			attackable = true,
			barricadeable = true,
		},
		passage = { kind = "walkable" },
		natural_rotation = 0,
		interaction = {
			toggle = {
				natural_rotation = 0,
				appearance = {
					chars = { ":", ":" },
				},
				tags = {
					solid = false,
					walkable = true,
					barricadeable = false,
				},
			},
		},
	},
	window = {
		name = "Window",
		description = "A window, try opening it!",
		type = "prop",
		appearance = {
			chars = { " ", "--", "--" },
			color = { { 0.55, 0.35, 0.1, 1 }, { 0.30, 0.16, 0.06, 1 }, { 0.30, 0.16, 0.06, 1 } },
		},
		default_action = "interactable",
		tags = {
			solid = true,
			walkable = false,
			tilelike = true,
			interactable = true,
			vaultable = false,
			barricadeable = true,
			attackable = true,
		},
		stats = {
			health = { base = 10, current = 10 },
		},
		combat = { hit_burst = "dust" },
		corpse = "broken_window",
		passage = { kind = "vaultable" },
		natural_rotation = 90,
		interaction = {
			toggle = {
				appearance = {
					chars = { " ", "''", "''" },
				},
				default_action = "vaultable",
				natural_rotation = 90,
				tags = {
					solid = false,
					walkable = false,
					barricadeable = false,
					vaultable = true,
					attackable = true,
				},
			},
		},
	},

	broken_window = {
		name = "Broken Window",
		description = "A broken window, try climbing through it!",
		type = "prop",
		appearance = {
			chars = { " ", "'", "'" },
			color = { { 0.55, 0.35, 0.1, 1 }, { 0.30, 0.16, 0.06, 1 }, { 0.30, 0.16, 0.06, 1 } },
		},
		default_action = "vaultable",
		passage = { kind = "vaultable" },
		tags = {
			solid = false,
			walkable = false,
			tilelike = true,
			vaultable = true,
		},
		natural_rotation = 90,
	},

	street_lamp = {
		name = "Street Lamp",
		type = "prop",
		appearance = {
			chars = { ".", ".", ".", ".", ".", ".", ".", "#" },
			color = {
				{ 0.55, 0.35, 0.1, 1 },
				{ 0.55, 0.35, 0.1, 1 },
				{ 0.55, 0.35, 0.1, 1 },
				{ 0.55, 0.35, 0.1, 1 },
				{ 0.55, 0.35, 0.1, 1 },
				{ 0.55, 0.35, 0.1, 1 },
				{ 0.55, 0.35, 0.1, 1 },
				{ 0.7, 0.55, 0.25, 1 },
			},
		},
		description = "A Street Lamp",
		tags = {
			solid = true,
			moveable = true,
			tilelike = true,
			covers = true,
		},
		light = {
			color = { r = 0.8, g = 0.65, b = 0.45 },
			flicker = { amp = 0.01, freq = 4, phase = 4 },
			intensity = 0.7,
			radius = 9,
		},
	},
}
