return {
	player = {
		chars = { "@" },
		color = { { 0.8, 0.8, 0.9, 1 } },
		effect_color = { 0.45, 0.45, 0.5, 0.5 },
		name = "Player",
		type = "actor",
		tags = { covers = true, attackable = true },
		default_action = "attackable",
		allowed_actions = {
			attackable = true,
			moveable = true,
			interactable = true,
			pickupable = true,
		},
		stats = {
			health = { base = 25, current = 25 },
			stamina = { base = 10, current = 10 },
			hunger = { base = 10, current = 10 },
			sight = { base = 30 },
			speed = { base = 5 },
			damage = { base = 1 },
		},

		next_turn = 0,
	},
	zombie = {
		name = "Zombie",
		type = "actor",
		team = "enemy",
		state = "idle",
		chars = { "Z" },
		color = { { 0.3, 0.45, 0.25, 1 } },
		effect_color = { 0.35, 0.6, 0.3, 0.5 },
		description = "A zombie, try attacking it!",
		default_action = "attackable",
		stats = {
			health = { base = 10, current = 10 },
			sight = { base = 30 },
			speed = { base = 4 },
			damage = { base = 1 },
		},
		tags = {
			solid = false,
			moveable = true,
			tilelike = false,
			covers = true,
			attackable = true,
			walkable = false,
		},
		allowed_actions = {
			attackable = true,
		},
		applies_on_hit = { { name = "poison", chance = 50 } },
		next_turn = 0,
	},
	vampire = {
		name = "Vampire",
		type = "actor",
		team = "enemy",
		state = "idle",
		chars = { "V" },
		color = { { 0.7, 0.2, 0.2, 1 } },
		effect_color = { 0.35, 0.1, 0.1, 0.5 },
		description = "A vampire, try attacking it!",
		default_action = "attackable",
		stats = {
			health = { base = 10, current = 10 },
			sight = { base = 30 },
			speed = { base = 6 },
			damage = { base = 1 },
		},
		tags = {
			solid = false,
			moveable = true,
			tilelike = false,
			covers = true,
			attackable = true,
			walkable = false,
		},
		allowed_actions = {
			attackable = true,
		},
		next_turn = 0,
	},
	tree = {
		name = "Tree",
		type = "prop",
		chars = { ".", ".", ".", "*" },
		color = { { 0.75, 0.35, 0.1, 1 }, { 0.75, 0.35, 0.1, 1 }, { 0.75, 0.35, 0.1, 1 }, { 0.3, 0.75, 0.25, 1 } },
		description = "A Tree",
		tags = {
			solid = true,
			moveable = true,
			tilelike = true,
			covers = true,
			attackable = false,
			walkable = false,
		},
	},
	campfire = {
		name = "Campfire",
		type = "prop",
		chars = { "%" },
		color = { { 1, 0.35, 0.1, 1 } },
		description = "A Campfire",
		tags = {
			solid = false,
			moveable = false,
			tilelike = true,
			covers = true,
			attackable = false,
			walkable = false,
		},
		light = {
			color = { r = 1.0, g = 0.6, b = 0.25 },
			intensity = 1,
			radius = 10,
			flicker = { amp = 0.05, freq = 2, phase = 3 },
		},
	},
	crystal = {
		name = "Crystal",
		type = "prop",
		chars = { "<>", "<>" },
		color = { { 0.7, 0.9, 0.95, 1 } },
		description = "A Crystal",
		default_action = "moveable",
		tags = {
			solid = false,
			moveable = true,
			tilelike = true,
			covers = true,
			attackable = false,
			walkable = false,
		},
		light = {
			color = { r = 0.7, g = 0.9, b = 1 },
			intensity = 0.8,
			radius = 7,
			flicker = { amp = 0.1, freq = 4, phase = 0 },
		},
	},
	crate = {
		name = "Crate",
		description = "A heavy crate, try pushing it!",
		type = "prop",
		chars = { "#" },
		color = { { 0.38, 0.33, 0.30 } },
		default_action = "moveable",
		tags = {
			solid = false,
			moveable = true,
			tilelike = true,
			covers = true,
			walkable = false,
		},
	},
	item = {
		name = "Item",
		description = "An item, try picking it up!",
		type = "prop",
		chars = { "*" },
		color = { { 1, 1, 0, 1 } },
		default_action = "pickupable",
		tags = {
			solid = false,
			tilelike = true,
			covers = true,
			walkable = false,
			pickupable = true,
		},
	},
	barricade = {
		name = "Barricade",
		description = "A heavy barricade, try pushing it!",
		type = "prop",
		chars = { "[]", "[]" },
		color = { { 0.47, 0.23, 0.23, 1 } },
		default_action = "moveable",
		tags = {
			solid = true,
			moveable = true,
			tilelike = true,
			covers = true,
			walkable = false,
		},
	},
	door = {
		name = "Door",
		description = "A door, try opening it!",
		type = "prop",
		chars = { "[", "[" },
		color = { { 0.47, 0.23, 0.23, 1 } },
		default_action = "interactable",
		tags = {
			moveable = false,
			solid = true,
			walkable = false,
			tilelike = true,
			interactable = true,
			covers = false,
		},
		natural_rotation = 0,
		interaction = {
			toggle = {
				natural_rotation = 0,
				chars = { ":", ":" },
				tags = {
					solid = false,
					walkable = true,
				},
			},
		},
	},
	window = {
		name = "Window",
		description = "A window, try opening it!",
		type = "prop",
		chars = { " ", "--", "--" },
		color = { { 0.47, 0.33, 0.23, 1 } },
		default_action = "interactable",
		tags = {
			moveable = false,
			solid = true,
			walkable = false,
			tilelike = true,
			interactable = true,
			covers = false,
		},
		natural_rotation = 90,
		interaction = {
			toggle = {
				chars = { " ", "''", "''" },
				natural_rotation = 90,
				tags = {
					solid = false,
					walkable = false,
				},
			},
		},
	},
}
