return {
	use_pixel_font = true,
	font_scale = 2,
	font_base_size = 16,
	debug_font_scale = 0.5,
	draw_distance = 50,
	max_height = 5,
	default_offset_type = 1,
	offset_amount_factor = 0.25,
	camera_speed = 2,
	show_grid = false,
	grid_color = { 0.5, 0.5, 0.5, 0.1 },
	distance_drama = 0.66,
	brightness = 1,
	bw_mode = false,
	show_brightness_debug = false,
	z_size_scale_per_level = 0.03,
	entity_brightness_boost = 0.3,
	shadow_brightness_scale = 0.25,
	shadow_alpha_scale = 0.7,
}
