return {
  typeKeys = {
    "crimson",
    "orange",
    "pink",
    "yellow",
    "gold",
    "chartreuse",
    "turquoise",
    "springgreen",
    "cyan",
    "deepskyblue",
    "plum",
    "violet",
    "teal",
    "blue",
    "magenta",
    "purple",
    "indigo",
    "red",
    "maroon",
    "navy",
  },
  crimson = { name = "floor", chars = { "::" }, walkable = true, color = { 1.0, 0.4, 0.4, 1 }, transparent = true },
  orange = { name = "floor", chars = { "::" }, walkable = true, color = { 1.0, 0.58, 0.4, 1 }, transparent = true },
  pink = { name = "floor", chars = { "::" }, walkable = true, color = { 1.0, 0.76, 0.4, 1 }, transparent = true },
  yellow = { name = "floor", chars = { "::" }, walkable = true, color = { 1.0, 0.94, 0.4, 1 }, transparent = true },
  gold = { name = "floor", chars = { "::" }, walkable = true, color = { 0.88, 1.0, 0.4, 1 }, transparent = true },
  chartreuse = { name = "floor", chars = { "::" }, walkable = true, color = { 0.7, 1.0, 0.4, 1 }, transparent = true },
  turquoise = { name = "floor", chars = { "::" }, walkable = true, color = { 0.52, 1.0, 0.4, 1 }, transparent = true },
  springgreen = { name = "floor", chars = { "::" }, walkable = true, color = { 0.4, 1.0, 0.46, 1 }, transparent = true },
  cyan = { name = "floor", chars = { "::" }, walkable = true, color = { 0.4, 1.0, 0.64, 1 }, transparent = true },
  deepskyblue = { name = "floor", chars = { "::" }, walkable = true, color = { 0.4, 1.0, 0.82, 1 }, transparent = true },
  plum = { name = "floor", chars = { "::" }, walkable = true, color = { 0.4, 1.0, 1.0, 1 }, transparent = true },
  violet = { name = "floor", chars = { "::" }, walkable = true, color = { 0.4, 0.82, 1.0, 1 }, transparent = true },
  teal = { name = "floor", chars = { "::" }, walkable = true, color = { 0.4, 0.64, 1.0, 1 }, transparent = true },
  blue = { name = "floor", chars = { "::" }, walkable = true, color = { 0.4, 0.46, 1.0, 1 }, transparent = true },
  magenta = { name = "floor", chars = { "::" }, walkable = true, color = { 0.52, 0.4, 1.0, 1 }, transparent = true },
  purple = { name = "floor", chars = { "::" }, walkable = true, color = { 0.7, 0.4, 1.0, 1 }, transparent = true },
  indigo = { name = "floor", chars = { "::" }, walkable = true, color = { 0.88, 0.4, 1.0, 1 }, transparent = true },
  red = { name = "floor", chars = { "::" }, walkable = true, color = { 1.0, 0.4, 0.94, 1 }, transparent = true },
  maroon = { name = "floor", chars = { "::" }, walkable = true, color = { 1.0, 0.4, 0.76, 1 }, transparent = true },
  navy = { name = "floor", chars = { "::" }, walkable = true, color = { 1.0, 0.4, 0.58, 1 }, transparent = true },
}
