return {
	poison = {
		name = "Poison",
		description = "Losing health over time.",
		color = { 0.5, 1, 0.5 },
		duration = 5,
		on_tick = { damage = 1 },
	},
	regen = {
		name = "Regeneration",
		description = "Gaining health over time.",
		color = { 1, 0.5, 0.5 },
		duration = 5,
		on_tick = { heal = 3 },
		emitters = { { particle = "heal", rate = 2, jitter = true } },
		visual = { tint = { 0.5, 1, 0.5 } },
	},
	strength = {
		name = "Strength",
		description = "Increased damage.",
		color = { 0.75, 0.75, 0.5 },
		duration = 5,
		modifiers = {
			{ stat = "damage", op = "add", value = 3 },
		},
	},

	glowing = {
		name = "Glowing",
		description = "Glowing.",
		color = { 0.75, 0.75, 0.5 },
		light = {
			color = { r = 1.0, g = 0.85, b = 0.65 },
			flicker = { amp = 0.1, freq = 2, phase = 6 },
			intensity = 0.25,
			radius = 12,
		},
		duration = 5,
	},

	burning = {
		name = "Burning",
		description = "Taking damage over time.",
		color = { 0.75, 0.6, 0.4 },
		light = {
			color = { r = 1.0, g = 0.6, b = 0.25 },
			intensity = 0.7,
			radius = 5,
			flicker = { amp = 0.02, freq = 2, phase = 3 },
		},
		emitters = { { particle = "smoke", rate = 1 }, { particle = "ember", rate = 1.2 } },
		duration = 7,
		on_tick = { damage = 1, chance = 50 },
	},
	stun = {
		name = "Stun",
		description = "Unable to move or act.",
		tags = { disables_action = true },
		emitters = { { particle = "dazed", rate = 5, jitter = true } },
		color = { 0.5, 0.5, 1 },
		duration = 2,
	},
	obscured = {
		name = "Obscured",
		description = "Reduced sight range and increased stealth.",
		color = { 0.5, 1, 0.5 },
		duration = 1,
		modifiers = {
			{ stat = "sight", op = "mul", value = 0.5 },
			{ stat = "stealth", op = "mul", value = 2 },
		},
		visual = { alpha = 0.5 },
	},
	barricaded = {
		name = "Barricaded",
		description = "Blocked interaction and increased health.",
		color = { 1, 0.8, 0.5 },
		hp = 5,
		tags = { absorbs = true, disables_interaction = true, remove_when_empty = true },
		visual = { tint = { 1, 0.8, 0.5 } },
	},
	bleeding = {
		name = "Bleeding",
		description = "Losing health over time.",
		color = { 1, 0.5, 0.6 },
		visual = { tint = { 0.6, 0.35, 0.3 } },
		emitters = { { particle = "blood", rate = 2, z_offset = 0, jitter = true } },
		duration = 40,
		tags = { bandageable = true },
		on_tick = { damage = 1, chance = 25 },
	},
	broken_leg = {
		name = "Broken Leg",
		description = "Decreased movement speed.",
		color = { 1, 0.5, 0.6 },
		modifiers = {
			{ stat = "speed", op = "mul", value = 0.66 },
		},
		tags = { splintable = true },
	},
}
